#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

sh ./pre-commit/pre-commit.sh
sh ./pre-commit/pre-commit.sh
sh ./pre-commit/pre-commit.sh
sh ./pre-commit/pre-commit.sh
sh ./pre-commit/pre-commit.sh
